CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'buyer',
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE musicians (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL,
    instruments VARCHAR(500),
    birth_year INTEGER,
    country VARCHAR(100)
);

CREATE TABLE companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    phone VARCHAR(50),
    email VARCHAR(255),
    is_wholesaler BOOLEAN DEFAULT FALSE
);

CREATE TABLE ensembles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    founded_year INTEGER,
    country VARCHAR(100),
    description TEXT
);

CREATE TABLE ensemble_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ensemble_id INTEGER NOT NULL,
    musician_id INTEGER NOT NULL,
    role_in_ensemble VARCHAR(100),
    joined_year INTEGER,
    FOREIGN KEY (ensemble_id) REFERENCES ensembles(id) ON DELETE CASCADE,
    FOREIGN KEY (musician_id) REFERENCES musicians(id) ON DELETE CASCADE
);

CREATE TABLE compositions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    composer_id INTEGER,
    genre VARCHAR(100),
    year_composed INTEGER,
    duration_minutes INTEGER,
    FOREIGN KEY (composer_id) REFERENCES musicians(id) ON DELETE SET NULL
);

CREATE TABLE performances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composition_id INTEGER NOT NULL,
    ensemble_id INTEGER NOT NULL,
    conductor_id INTEGER,
    recording_date DATE,
    venue VARCHAR(255),
    FOREIGN KEY (composition_id) REFERENCES compositions(id) ON DELETE CASCADE,
    FOREIGN KEY (ensemble_id) REFERENCES ensembles(id) ON DELETE CASCADE,
    FOREIGN KEY (conductor_id) REFERENCES musicians(id) ON DELETE SET NULL
);

CREATE TABLE records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_number VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    company_id INTEGER NOT NULL,
    release_date DATE,
    wholesale_price DECIMAL(10,2),
    retail_price DECIMAL(10,2),
    current_stock INTEGER DEFAULT 0,
    sold_last_year INTEGER DEFAULT 0,
    sold_this_year INTEGER DEFAULT 0,
    rating DECIMAL(3,2),
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE record_tracks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id INTEGER NOT NULL,
    performance_id INTEGER NOT NULL,
    track_number INTEGER,
    FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE CASCADE,
    FOREIGN KEY (performance_id) REFERENCES performances(id) ON DELETE CASCADE
);

CREATE TABLE cart (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    record_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE CASCADE
);

CREATE TABLE purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    record_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price DECIMAL(10,2) NOT NULL,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    seller_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE CASCADE,
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE SET NULL
);
